# Generated by Django 5.0.2 on 2024-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_email', models.CharField(max_length=200)),
                ('person_contact', models.CharField(max_length=200)),
                ('person_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('timeperiod', models.CharField(max_length=100)),
                ('work_done', models.TextField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
