# Generated by Django 5.0.2 on 2024-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_history_score_alter_history_skill_set_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='degination',
            new_name='designation',
        ),
    ]
