# Generated by Django 5.0.2 on 2024-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_degination_history_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weather/static/'),
        ),
    ]
