# Generated by Django 5.0.2 on 2024-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_history_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
        migrations.AddField(
            model_name='history',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
